FROM ubuntu:16.04

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive \
apt-get install -y \
build-essential \
libjansson-dev \
autotools-dev \
automake \
apt-get install -y sudo \
clang \
binutils \
git \
libicu-dev \
wget \
libxml2 \
libcurl3 \
curl \
&& rm -r /var/lib/apt/lists/*







